language: ruby
os: linux
rvm:
  - 2.3.0
services:
  - postgresql
addons:
  postgresql: "9.4"

before_install:
  - gem install mime-types -v 2.6.2
  - gem install bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:drop db:create db:migrate RAILS_ENV=test
script: "bundle exec rspec spec"
